'use client'

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

/**
 * 個人成績証明書をPDF出力
 * ※日本語フォント非対応のため英語表記
 * @param {Object} student - 学生データ
 * @param {string} yearTerm - 学期
 */
export function exportStudentGradeToPDF(student, yearTerm) {
    if (!student) {
        alert('エクスポートするデータがありません')
        return
    }

    try {
        // 評価計算
        const calculateGrade = (score) => {
            if (score >= 80) return 'A'
            if (score >= 60) return 'B'
            if (score >= 40) return 'C'
            if (score >= 20) return 'D'
            return 'F'
        }

        // 出席点・参加点を取得
        const attendanceScore = student.report_card_data?.attendance || 0
        const participationScore = student.report_card_data?.participation || 0

        // 学期を安全な形式に変換
        const formatTerm = (term) => {
            if (!term) return '-'
            const match = term.match(/(\d{4})/)
            if (match) {
                const year = match[1]
                if (term.includes('前期')) return `${year} Spring`
                if (term.includes('後期')) return `${year} Fall`
                return year
            }
            return term.replace(/[^\x00-\x7F]/g, '')
        }

        // PDFドキュメント作成
        const doc = new jsPDF('p', 'mm', 'a4')

        // ヘッダー
        doc.setFontSize(22)
        doc.setFont('helvetica', 'bold')
        doc.text('GRADE REPORT', 105, 25, { align: 'center' })

        doc.setFontSize(12)
        doc.setFont('helvetica', 'normal')
        doc.text('Kobe Gaigo Language School', 105, 33, { align: 'center' })

        doc.setFontSize(10)
        doc.text(`Issue Date: ${new Date().toLocaleDateString('en-US')}`, 105, 40, { align: 'center' })

        doc.setDrawColor(200)
        doc.line(20, 45, 190, 45)

        // 学生情報
        doc.setFontSize(13)
        doc.setFont('helvetica', 'bold')
        doc.text('STUDENT INFORMATION', 20, 55)

        doc.setFont('helvetica', 'normal')
        doc.setFontSize(11)
        doc.text(`Student ID: ${student.student_id_text || '-'}`, 20, 65)
        doc.text(`Name: ${student.student_name || '-'}`, 20, 72)
        doc.text(`Class: ${student.class_name || '-'}`, 20, 79)
        doc.text(`Term: ${formatTerm(yearTerm)}`, 20, 86)

        // 成績概要
        doc.setFontSize(13)
        doc.setFont('helvetica', 'bold')
        doc.text('GRADE SUMMARY', 20, 100)

        const summaryData = [
            ['Final Exam Score', `${student.final_exam_total || 0} / 600`],
            ['Report Card Score', `${student.report_card_total || 0} / 100`],
            ['Attendance Score', `${typeof attendanceScore === 'number' ? attendanceScore.toFixed(1) : attendanceScore}`],
            ['Participation Score', `${typeof participationScore === 'number' ? participationScore.toFixed(1) : participationScore}`],
            ['Overall Grade', calculateGrade(student.report_card_total)]
        ]

        autoTable(doc, {
            startY: 105,
            head: [['Category', 'Result']],
            body: summaryData,
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246], textColor: 255 },
            styles: { fontSize: 10 },
            margin: { left: 20, right: 20 },
            tableWidth: 170
        })

        // 科目別詳細
        if (student.report_card_data) {
            const subjectNames = {
                'vocab': 'Vocabulary',
                'grammar': 'Grammar',
                'reading': 'Reading',
                'listening': 'Listening',
                'writing': 'Writing',
                'conversation': 'Conversation'
            }

            const subjectData = Object.entries(student.report_card_data)
                .filter(([key]) => subjectNames[key])
                .map(([key, data]) => [
                    subjectNames[key] || key,
                    typeof data.base === 'number' ? data.base.toFixed(1) : '0',
                    typeof data.total === 'number' ? data.total.toFixed(1) : '0'
                ])

            if (subjectData.length > 0) {
                doc.setFontSize(13)
                doc.setFont('helvetica', 'bold')
                doc.text('SUBJECT DETAILS', 20, doc.lastAutoTable.finalY + 15)

                autoTable(doc, {
                    startY: doc.lastAutoTable.finalY + 20,
                    head: [['Subject', 'Base Score', 'Total']],
                    body: subjectData,
                    theme: 'striped',
                    headStyles: { fillColor: [59, 130, 246], textColor: 255 },
                    styles: { fontSize: 10 },
                    margin: { left: 20, right: 20 },
                    tableWidth: 170
                })
            }
        }

        // フッター
        const pageHeight = doc.internal.pageSize.height
        doc.setDrawColor(200)
        doc.line(20, pageHeight - 25, 190, pageHeight - 25)

        doc.setFontSize(8)
        doc.setTextColor(128)
        doc.text('This document is automatically generated by Kobe Gaigo LMS.', 105, pageHeight - 18, { align: 'center' })
        doc.text('For official records, please contact the administration office.', 105, pageHeight - 13, { align: 'center' })

        // ファイル名
        const safeYearTerm = formatTerm(yearTerm).replace(/\s/g, '_')
        const fileName = `Grade_Report_${student.student_id_text}_${safeYearTerm}.pdf`

        doc.save(fileName)

    } catch (error) {
        console.error('PDF generation error:', error)
        alert('PDFの生成に失敗しました: ' + error.message)
    }
}
