'use client'

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

/**
 * Export individual student grade certificate as PDF
 * Note: Using English text only because jsPDF default fonts don't support Japanese
 * @param {Object} student - Student data
 * @param {string} yearTerm - Academic term
 */
export function exportStudentGradeToPDF(student, yearTerm) {
    if (!student) {
        alert('No data to export')
        return
    }

    // Grade calculation function
    const calculateGrade = (score) => {
        if (score >= 80) return 'A'
        if (score >= 60) return 'B'
        if (score >= 40) return 'C'
        if (score >= 20) return 'D'
        return 'F'
    }

    // Create PDF document (A4 size)
    const doc = new jsPDF('p', 'mm', 'a4')

    // Header
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('GRADE REPORT', 105, 25, { align: 'center' })

    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    doc.text('Kobe Gaigo Language School', 105, 33, { align: 'center' })

    doc.setFontSize(10)
    doc.text(`Issue Date: ${new Date().toLocaleDateString('en-US')}`, 105, 40, { align: 'center' })

    // Divider line
    doc.setDrawColor(200)
    doc.line(20, 45, 190, 45)

    // Student Information
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('STUDENT INFORMATION', 20, 55)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.text(`Student ID: ${student.student_id_text || '-'}`, 20, 65)
    doc.text(`Name: ${student.student_name || '-'}`, 20, 72)
    doc.text(`Class: ${student.class_name || '-'}`, 20, 79)
    doc.text(`Term: ${yearTerm || '-'}`, 20, 86)

    // Grade Summary
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('GRADE SUMMARY', 20, 100)

    const summaryData = [
        ['Final Exam Score', `${student.final_exam_total || 0} / 600`],
        ['Report Card Score', `${student.report_card_total || 0} / 100`],
        ['Overall Grade', calculateGrade(student.report_card_total)]
    ]

    autoTable(doc, {
        startY: 105,
        head: [['Category', 'Result']],
        body: summaryData,
        theme: 'striped',
        headStyles: { fillColor: [59, 130, 246], textColor: 255 },
        styles: { fontSize: 10 },
        margin: { left: 20, right: 20 },
        tableWidth: 170
    })

    // Subject Details (if data exists)
    if (student.report_card_data) {
        const subjectNames = {
            'vocab': 'Vocabulary',
            'grammar': 'Grammar',
            'reading': 'Reading',
            'listening': 'Listening',
            'writing': 'Writing',
            'conversation': 'Conversation'
        }

        const subjectData = Object.entries(student.report_card_data)
            .filter(([key]) => subjectNames[key])
            .map(([key, data]) => [
                subjectNames[key] || key,
                data.base?.toFixed(1) || '0',
                data.attendance || '0',
                data.participation || '0',
                data.total?.toFixed(1) || '0'
            ])

        if (subjectData.length > 0) {
            doc.setFontSize(12)
            doc.setFont('helvetica', 'bold')
            doc.text('SUBJECT DETAILS', 20, doc.lastAutoTable.finalY + 15)

            autoTable(doc, {
                startY: doc.lastAutoTable.finalY + 20,
                head: [['Subject', 'Base', 'Attend.', 'Partic.', 'Total']],
                body: subjectData,
                theme: 'striped',
                headStyles: { fillColor: [59, 130, 246], textColor: 255 },
                styles: { fontSize: 10 },
                margin: { left: 20, right: 20 },
                tableWidth: 170
            })
        }
    }

    // Footer
    const pageHeight = doc.internal.pageSize.height
    doc.setDrawColor(200)
    doc.line(20, pageHeight - 25, 190, pageHeight - 25)

    doc.setFontSize(8)
    doc.setTextColor(128)
    doc.text('This document is automatically generated by Kobe Gaigo LMS.', 105, pageHeight - 18, { align: 'center' })
    doc.text('For official records, please contact the administration office.', 105, pageHeight - 13, { align: 'center' })

    // Generate filename
    const fileName = `Grade_Report_${student.student_id_text}_${yearTerm.replace(/\s/g, '_')}.pdf`

    // Save PDF
    doc.save(fileName)
}
